#!/bin/bash -vx
#
# HTTP_ACCRESS_NORMALIZE accrss_logの正規化
# usage: ./HTTP_ACCESS_NORMALIZE
#
# written by R. Ueda (USP研究所) Nov. 29, 2011
dir=/var/www/html/GIHYO

dlmt=あ
reg='^\(..*\) \(..*\) \(..*\) \[\(..*\)\] "\(..*\)" \(..*\) \(..*\) "\(..*\)" "\(..*\)"$'
str="\\1$dlmt\\2$dlmt\\3$dlmt\\4$dlmt\\5$dlmt\\6$dlmt\\7$dlmt\\8$dlmt\\9"

sed 's/""/"-"/g' $dir/LOG/httpd/access_{log.*,log}	|
#"や[ ]、空白を目印にレコードを9分割する。
sed "s;$reg;$str;" 					|
#_を\_に
sed 's/_/\\_/g'						|
#空白を_に
sed 's/ /_/g'						|
#デリミタを空白に戻す
sed "s/$dlmt/ /g"					|
#出力例：119.147.75.140 - - 23/Nov/2011:15:14:13_+0900 ...
#日時を先頭に
awk '{a=$4;$4="";print a,$0}'				|
#出力例：23/Nov/2011:15:14:13_+0900 119.147.75.140 - - ...
sed 's;^\(..\)/\(...\)/\(....\):\(..\):\(..\):\(..\)_[^ ]*;\2 \1 \3 \4\5\6;'	|
#出力例：Nov 23 2011 151413 119.147.75.140 - - ...
sed -f $dir/SYS/MONTH					|
#出力例：11 23 2011 151413 119.147.75.140 - - ...
awk '{d=$3$1$2;$1="";$2="";$3="";print d,$0}'		|
#1:日付 2:時刻 3-10:あとの項目
#間延びした区切りの空白を戻す。
sed 's/  */ /g'	> $dir/LOG/ACCESS_LOG

exit 0
