#!/bin/bash

tmp=/tmp/$$

awk '{  print "<tr>";
	for(i=1;i<=NF;i++){print "<td>"$i"</td>"};
	print "</tr>" }' ./HOMER > $tmp-table

tee $tmp-html << EOF
<!DOCTYPE html>
<html>
	<head><meta charset="utf-8" /></head>
	<body>
		<h1 style="font-size:18px">通算本塁打</h1>
		<table border="1" cellspacing="0">
$(cat $tmp-table)
		</table>
	</body>
</html>
EOF

firefox $tmp-html
rm -f $tmp-*
